ngrok-webapi:
  restart: always
  image: keepwn/ngrok-webapi
  ports:
    - 5000:5000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./ngrok-bin:/ngrok-bin
    - ./ngrok-data:/ngrok-webapi/data

ngrok-webui:
  restart: always
  image: nginx
  volumes:
    - ./ngrok.template:/etc/nginx/conf.d/ngrok.template
    - ./ngrok-webui:/usr/share/nginx/html
  net: host
  environment:
    - NGINX_PORT=8080
    - NGINX_HOST=localhost
    - NGROK_WEBAPI_HOST=127.0.0.1
    - NGROK_WEBAPI_PORT=5000
  command: /bin/sh -c "envsubst < /etc/nginx/conf.d/ngrok.template > /etc/nginx/conf.d/default.conf &&nginx -g 'daemon off;'"
